version: '3.8'

services:
  navigator:
    build:
      context: .
      dockerfile: Dockerfile
    image: veil
    ports:
      - "4200:4200"
    volumes:
      - ./data:/src/nav-app/src/assets/data

